services:
  postgres:
    image: postgres:16-alpine
    container_name: clarity-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clarity
    ports:
      - '5432:5432'

  adminer:
    image: adminer:latest
    container_name: clarity-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula
